server:
  port: 8090
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        username: nacos
        password: nacos
        namespace: public
      config:
        server-addr: localhost:8848
        namespace: public  # 指定配置文件的命名空间为 public
        file-extension: yaml
  config:
    import:
      - optional:nacos:gateway.yaml #可能不存在配置文件